services:
  cleanbot:
    container_name: cleanbot-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET_ENV: dev
    restart: unless-stopped
    env_file:
      - .env
